twitter_feed.settings:
  type: config_object
  label: 'Twitter Feed settings form Map.'
  mapping:
    twitter_feed_api_key:
      type: text
      label: 'API Key'
    twitter_feed_api_secret:
      type: text
      label: 'API Secret'
    twitter_feed_jquery_timeago_locale:
      type: label
      label: 'jQuery Timeago locale'

block.settings.twitter_feed_block:
  type: block_settings
  mapping:
    number_of_tweets:
      type: label
      label: Number of tweets
    username:
      type: label
      label: Username to display
    display_images:
      type: boolean
      label: Display images
    display_avatars:
      type: boolean
      label: Display avatars
